### ISSUE TITLE
vcp issue 500

### ISSUE THREAD

**Issue by sfabbro** [canfar/live#6]
This Github issue is synchronized with Zendesk,

**Ticket ID:** [2](https://canfar.zendesk.com/agent/#/tickets/2)
**Priority:** N/A
**Group:** Support
**Assignee:** Sébastien Fabbro

**Original ticket description:**

getting this all the freaking time

**Comment by sfabbro** [comment]
*Comment made from Zendesk by Sébastien Fabbro on 2015-09-10 at 19:14:*

<div class="zd-comment"><p>this is true!</p></div>

**Comment by sfabbro** [comment]
*Comment made from Zendesk by Sébastien Fabbro on 2015-09-10 at 19:15:*

<div class="zd-comment"><p>ok thanks</p></div>

**Comment by sfabbro** [comment]
new comment from github to zendesk

**Comment by sfabbro** [comment]
closing from github

**Comment by sfabbro** [comment]
*Comment made from Zendesk by Sébastien Fabbro on 2015-09-11 at 03:49:*

<div class="zd-comment"><p>This GitHub issue has been closed by sfabbro on 2015-09-11 at 03:49.</p></div>

**Comment by ijiraq** [comment]
I think the solution you found is wrong and this does not resolve issue #6
